// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decisions.sql

package db

import (
	"context"
)

const addPick = `-- name: AddPick :exec
INSERT INTO picks (document_id, item_id) VALUES (?, ?)
ON CONFLICT (document_id, item_id) DO NOTHING
`

type AddPickParams struct {
	DocumentID string
	ItemID     string
}

func (q *Queries) AddPick(ctx context.Context, arg AddPickParams) error {
	_, err := q.db.ExecContext(ctx, addPick, arg.DocumentID, arg.ItemID)
	return err
}

const deleteNotes = `-- name: DeleteNotes :exec
DELETE FROM notes WHERE document_id = ?
`

func (q *Queries) DeleteNotes(ctx context.Context, documentID string) error {
	_, err := q.db.ExecContext(ctx, deleteNotes, documentID)
	return err
}

const deletePicks = `-- name: DeletePicks :exec
DELETE FROM picks WHERE document_id = ?
`

func (q *Queries) DeletePicks(ctx context.Context, documentID string) error {
	_, err := q.db.ExecContext(ctx, deletePicks, documentID)
	return err
}

const listNotes = `-- name: ListNotes :many
SELECT item_id, body FROM notes WHERE document_id = ? ORDER BY item_id
`

type ListNotesRow struct {
	ItemID string
	Body   string
}

func (q *Queries) ListNotes(ctx context.Context, documentID string) ([]ListNotesRow, error) {
	rows, err := q.db.QueryContext(ctx, listNotes, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotesRow
	for rows.Next() {
		var i ListNotesRow
		if err := rows.Scan(&i.ItemID, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPicks = `-- name: ListPicks :many
SELECT item_id FROM picks WHERE document_id = ? ORDER BY item_id
`

func (q *Queries) ListPicks(ctx context.Context, documentID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPicks, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var item_id string
		if err := rows.Scan(&item_id); err != nil {
			return nil, err
		}
		items = append(items, item_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putNote = `-- name: PutNote :exec
INSERT INTO notes (document_id, item_id, body) VALUES (?, ?, ?)
ON CONFLICT (document_id, item_id) DO UPDATE SET body = excluded.body
`

type PutNoteParams struct {
	DocumentID string
	ItemID     string
	Body       string
}

func (q *Queries) PutNote(ctx context.Context, arg PutNoteParams) error {
	_, err := q.db.ExecContext(ctx, putNote, arg.DocumentID, arg.ItemID, arg.Body)
	return err
}
