// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package db

import (
	"context"
)

const ensureDocument = `-- name: EnsureDocument :one
INSERT INTO documents (id, slug, decision_path, created_at, updated_at)
VALUES (?, ?, '', ?, ?)
ON CONFLICT (slug) DO UPDATE SET slug = excluded.slug
RETURNING id
`

type EnsureDocumentParams struct {
	ID        string
	Slug      string
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) EnsureDocument(ctx context.Context, arg EnsureDocumentParams) (string, error) {
	row := q.db.QueryRowContext(ctx, ensureDocument,
		arg.ID,
		arg.Slug,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getDecisionPath = `-- name: GetDecisionPath :one
SELECT decision_path FROM documents WHERE id = ?
`

func (q *Queries) GetDecisionPath(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getDecisionPath, id)
	var decision_path string
	err := row.Scan(&decision_path)
	return decision_path, err
}

const setDecisionPath = `-- name: SetDecisionPath :exec
UPDATE documents SET decision_path = ?1, updated_at = ?2 WHERE id = ?3
`

type SetDecisionPathParams struct {
	DecisionPath string
	UpdatedAt    string
	DocumentID   string
}

func (q *Queries) SetDecisionPath(ctx context.Context, arg SetDecisionPathParams) error {
	_, err := q.db.ExecContext(ctx, setDecisionPath, arg.DecisionPath, arg.UpdatedAt, arg.DocumentID)
	return err
}
