// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drafts.sql

package db

import (
	"context"
)

const deleteDraft = `-- name: DeleteDraft :exec
DELETE FROM drafts WHERE document_id = ? AND target = ?
`

type DeleteDraftParams struct {
	DocumentID string
	Target     string
}

func (q *Queries) DeleteDraft(ctx context.Context, arg DeleteDraftParams) error {
	_, err := q.db.ExecContext(ctx, deleteDraft, arg.DocumentID, arg.Target)
	return err
}

const deleteDrafts = `-- name: DeleteDrafts :exec
DELETE FROM drafts WHERE document_id = ?
`

func (q *Queries) DeleteDrafts(ctx context.Context, documentID string) error {
	_, err := q.db.ExecContext(ctx, deleteDrafts, documentID)
	return err
}

const getDraft = `-- name: GetDraft :one
SELECT target, base, value, updated_at FROM drafts WHERE document_id = ? AND target = ?
`

type GetDraftParams struct {
	DocumentID string
	Target     string
}

type GetDraftRow struct {
	Target    string
	Base      string
	Value     string
	UpdatedAt string
}

func (q *Queries) GetDraft(ctx context.Context, arg GetDraftParams) (GetDraftRow, error) {
	row := q.db.QueryRowContext(ctx, getDraft, arg.DocumentID, arg.Target)
	var i GetDraftRow
	err := row.Scan(
		&i.Target,
		&i.Base,
		&i.Value,
		&i.UpdatedAt,
	)
	return i, err
}

const listDrafts = `-- name: ListDrafts :many
SELECT target, base, value, updated_at FROM drafts WHERE document_id = ? ORDER BY target
`

type ListDraftsRow struct {
	Target    string
	Base      string
	Value     string
	UpdatedAt string
}

func (q *Queries) ListDrafts(ctx context.Context, documentID string) ([]ListDraftsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDrafts, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDraftsRow
	for rows.Next() {
		var i ListDraftsRow
		if err := rows.Scan(
			&i.Target,
			&i.Base,
			&i.Value,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putDraft = `-- name: PutDraft :exec
INSERT INTO drafts (document_id, target, base, value, updated_at) VALUES (?, ?, ?, ?, ?)
ON CONFLICT (document_id, target) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at
`

type PutDraftParams struct {
	DocumentID string
	Target     string
	Base       string
	Value      string
	UpdatedAt  string
}

func (q *Queries) PutDraft(ctx context.Context, arg PutDraftParams) error {
	_, err := q.db.ExecContext(ctx, putDraft,
		arg.DocumentID,
		arg.Target,
		arg.Base,
		arg.Value,
		arg.UpdatedAt,
	)
	return err
}
