// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Document struct {
	ID           string
	Slug         string
	DecisionPath string
	CreatedAt    string
	UpdatedAt    string
}

type Draft struct {
	DocumentID string
	Target     string
	Base       string
	Value      string
	UpdatedAt  string
}

type Note struct {
	DocumentID string
	ItemID     string
	Body       string
}

type Pick struct {
	DocumentID string
	ItemID     string
}

type Setting struct {
	DocumentID string
	Name       string
	Value      string
	UpdatedAt  string
}

type Verdict struct {
	DocumentID string
	ItemID     string
	Verdict    string
}
