// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"
)

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM settings WHERE document_id = ? AND name = ?
`

type DeleteSettingParams struct {
	DocumentID string
	Name       string
}

func (q *Queries) DeleteSetting(ctx context.Context, arg DeleteSettingParams) error {
	_, err := q.db.ExecContext(ctx, deleteSetting, arg.DocumentID, arg.Name)
	return err
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM settings WHERE document_id = ? AND name = ?
`

type GetSettingParams struct {
	DocumentID string
	Name       string
}

func (q *Queries) GetSetting(ctx context.Context, arg GetSettingParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, arg.DocumentID, arg.Name)
	var value string
	err := row.Scan(&value)
	return value, err
}

const putSetting = `-- name: PutSetting :exec
INSERT INTO settings (document_id, name, value, updated_at) VALUES (?, ?, ?, ?)
ON CONFLICT (document_id, name) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at
`

type PutSettingParams struct {
	DocumentID string
	Name       string
	Value      string
	UpdatedAt  string
}

func (q *Queries) PutSetting(ctx context.Context, arg PutSettingParams) error {
	_, err := q.db.ExecContext(ctx, putSetting,
		arg.DocumentID,
		arg.Name,
		arg.Value,
		arg.UpdatedAt,
	)
	return err
}
