package doors

import (
	"bytes"
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"dossier/internal/kinds"
	"dossier/internal/model"
)

func init() { register("skill", skillDoor) }

// SkillResult is dossier.skill-result/v1.
type SkillResult struct {
	SchemaVersion string `json:"schema_version"`
	Markdown      string `json:"markdown,omitempty"`
	Written       string `json:"written,omitempty"`
}

func (r SkillResult) human(w io.Writer) {
	if r.Written != "" {
		say(w, "wrote %s\n", r.Written)
		return
	}
	say(w, "%s", r.Markdown)
}

func skillDoor(_ context.Context, in Input) Envelope {
	args := in.Args
	const id = "skill"
	fs := flag.NewFlagSet(id, flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	write := fs.String("write", "", "write SKILL.md here instead of printing it")
	positional, err := parseInterspersed(fs, args)
	if err != nil {
		return errorEnvelope(id, "usage", err)
	}
	if len(positional) != 0 {
		return errorEnvelope(id, "usage", fmt.Errorf("skill takes no positional arguments"))
	}
	md, err := Skill()
	if err != nil {
		return errorEnvelope(id, "render", err)
	}
	if *write != "" {
		if err := os.MkdirAll(filepath.Dir(*write), 0o755); err != nil {
			return errorEnvelope(id, "write", err)
		}
		if err := os.WriteFile(*write, md, 0o644); err != nil {
			return errorEnvelope(id, "write", err)
		}
		return Envelope{SchemaVersion: SchemaVersion, Command: id, Outcome: OutcomeOK, Result: SkillResult{SchemaVersion: "dossier.skill-result/v1", Written: *write}}
	}
	return Envelope{SchemaVersion: SchemaVersion, Command: id, Outcome: OutcomeOK, Result: SkillResult{SchemaVersion: "dossier.skill-result/v1", Markdown: string(md)}}
}

// Skill renders SKILL.md from the catalog and the kinds, so the skill can
// never describe a command or a facet that the binary does not have.
func Skill() ([]byte, error) {
	catalog, err := LoadCatalog()
	if err != nil {
		return nil, err
	}
	all, err := kinds.All()
	if err != nil {
		return nil, err
	}
	var b bytes.Buffer
	w := func(format string, args ...any) { say(&b, format, args...) }

	var kindIDs []string
	for _, k := range all {
		kindIDs = append(kindIDs, k.ID)
	}
	w("---\n")
	w("name: dossier\n")
	w("description: Turn one JSON model into one self-contained, agent-readable HTML dossier (%s) that a reader scans once, decides on by number, and hands back as decisions. Use when the user wants a doc, plan, brief, report, review packet, release or incident record, or any structured decision surface.\n", strings.Join(kindIDs, ", "))
	w("metadata:\n  short-description: Render JSON document models into self-contained HTML dossiers\n")
	w("---\n\n")
	w("# Dossier\n\n")
	w("Generated by `dossier skill` from the command catalog and the kind presets; do not edit by hand.\n\n")
	w("Dossier turns **one JSON model** into **one self-contained HTML file**: no server, no external requests, the model embedded as a JSON island so an agent reads one block instead of scraping. The reader gets a contents rail, search, collapsed items, a summary table, and decision controls that write a reply line. You get the reply back as decisions.\n\n")

	w("## Five concepts\n\n")
	w("- **Kind** is a preset: what its items are, the fields and facets they carry, the sections a document has, and how the reader decides. Choose one below.\n")
	w("- **Section** has a title and either content parts or a board. Part types: %s.\n", strings.Join(model.PartTypes, ", "))
	w("- **Item** is a thing on a board: id, title, a one-sentence summary, the fields its kind declares, and facets. A board with `\"layout\": \"rows\"` lists unnumbered, free-form entries.\n")
	w("- **Facet** is a labeled Markdown body on an item. Labels come from the kind, in its order; required facets must be present.\n")
	w("- **Decision** is the only state: the option chosen, picked ids or verdicts by id, and notes by id. A kind may ask one question first, and a document's top-level `choice` (a question and two to six options with one-word ids) replaces it.\n\n")
	w("## Replies\n\n")
	w("A reply is one line: the choice when there is one, then picks or verdict groups by item number, then notes. `storms, 1, 3. Notes: 3: keep blue.` picks ideas 1 and 3. `rework, fix 1, 2; later 4; skip 6.` rules on review findings. Numbers without a verdict take the kind's default, `2-4` is a range, and `all` (or `rest`) covers every item not named elsewhere. `nothing` decides nothing. `dossier decisions apply` explains any reply it cannot read and names the words it accepts.\n\n")

	w("## Kinds\n\n")
	w("Run `dossier describe --json` for the full presets. `*` marks a required facet.\n\n")
	for _, k := range all {
		w("### %s\n\n", k.ID)
		w("%s Items are **%s**, %s.\n\n", k.Summary, k.Item.Plural, map[bool]string{true: "numbered", false: "unnumbered"}[k.Item.Numbered])
		if fields := fieldList(k); fields != "" {
			w("- **Fields:** %s.\n", fields)
		}
		w("- **Facets:**\n")
		for _, f := range k.Facets {
			mark := ""
			if f.Required {
				mark = "*"
			}
			w("  - %s%s: %s\n", f.Label, mark, f.Hint)
		}
		var sections []string
		for _, s := range k.Sections {
			label := "`" + s.ID + "`"
			switch {
			case s.Board && s.Repeat:
				label += " (boards, one per phase)"
			case s.Board:
				label += " (board)"
			case s.Layout == "rows":
				label += " (rows)"
			}
			if s.Optional {
				label += " optional"
			}
			sections = append(sections, label)
		}
		w("- **Sections:** %s.\n", strings.Join(sections, ", "))
		switch k.Decision.Mode {
		case kinds.ModeNone:
			w("- **Decision:** none; the reader only reads.\n\n")
		default:
			w("- **Decision:** %s.\n", itemLine(k)[strings.Index(itemLine(k), "; ")+2:])
			w("- **Reply:** %s For example `%s`\n\n", k.Decision.Markdown, k.Decision.Example)
		}
	}

	w("### Custom kinds\n\n")
	w("A team adds its own kinds without forking Dossier. Write one `ID.kind.json` file per kind in a directory, starting from a preset that `dossier describe --json` prints and leaving out its `source`, and pass `--kinds DIR` to any command or list directories in `%s`. Every command checks kind files first and answers with findings until they are valid; a custom kind cannot reuse a built-in id. `describe` shows where each kind came from, and `serve` and `mcp` pick up edits to kind files without a restart.\n\n", KindsEnv)
	w("## Content rules\n\n")
	w("- **Effort is agent time, never calendar time.** `S` is under an hour, `M` a few hours with review, `L` a day or more across sessions. Never write days-of-work or weeks-of-work.\n")
	w("- **Concise by default.** A summary is one sentence. A facet is two or three sentences. Kinds carry character limits; `validate` and `build` warn past them without blocking.\n")
	w("- **Detail sits behind a fold.** Items open collapsed, so the summary line must stand alone.\n")
	w("- **Ids** are lowercase letters, digits, and hyphens, unique across sections and items. `dependsOn` names item ids.\n")
	w("- **Markdown** in prose, facets, table cells, and spec text. Raw HTML is escaped. Fenced code is highlighted.\n")
	w("- **Figures** may use a path relative to the model file; `build` inlines it.\n")
	w("- **Diagrams** carry DOT or a Mermaid flowchart. `build` lays them out as SVG in the page's colors, with the source one click away. The classes teal, violet, risk, and accent mark nodes, edges, and clusters; other Mermaid diagram types stay as source with a warning.\n")
	w("- **Color is meaning.** Field values carry the kind's tones: teal for settled, violet for open, ochre for risk. Only the Risk facet is ochre.\n")
	w("- **One brand color.** `meta.theme.accent` (`#rrggbb`) recolors the accent. Light and dark variants are derived to keep text readable, and a color too light for text is darkened with a warning.\n\n")

	w("## Workflow\n\n")
	w("1. `dossier init KIND --title \"…\"` writes `<slug>.dossier.json` with the kind's sections and facets in place.\n")
	w("2. Fill it in: replace every hint with content, give each item a one-sentence summary and its required facets, and add optional facets only where they earn their place.\n")
	w("3. `dossier validate <slug>.dossier.json`: findings block, warnings are advice.\n")
	w("4. `dossier build <slug>.dossier.json` writes `<slug>.html` beside it. Open it for the reader. Add `--md` for a Markdown rendition to paste into a pull request, an issue, or a wiki.\n")
	w("5. The reader replies with one line in the kind's form. Apply it with `dossier decisions apply <slug>.dossier.json --reply \"…\"`, then rebuild.\n")
	w("6. `dossier decisions read <slug>.dossier.json` prints the decisions document for the next step.\n\n")
	w("Pass `--json` to any command for the `dossier.result/v1` envelope: `outcome` is `ok`, `findings`, or `error`; `findings` block, `warnings` do not. A 0.6 model file (`dossierVersion`, `blocks`) still builds, with one warning per aliased block; 0.8 removes the aliases.\n\n")

	w("## Commands\n\n")
	w("| Command | Does | Parameters |\n| --- | --- | --- |\n")
	for _, cmd := range catalog.Commands {
		if !cmd.Surfaced("skill") {
			continue
		}
		params, err := describeParameters(cmd)
		if err != nil {
			return nil, err
		}
		w("| `%s` | %s | %s |\n", usageLine(cmd), cmd.Summary, params)
	}
	w("\n`dossier mcp` serves the same commands as MCP tools over stdio, named %s, with the parameters above as their input schema and the same envelope as their answer.\n\n", mcpToolNames(catalog))

	w("## A starter model\n\n")
	brainstorm, err := kinds.Load("brainstorm")
	if err != nil {
		return nil, err
	}
	starter, err := model.Encode(Starter(brainstorm, "Twelve moves", "", ""))
	if err != nil {
		return nil, err
	}
	w("What `dossier init brainstorm --title \"Twelve moves\"` writes:\n\n```json\n%s```\n", starter)
	return b.Bytes(), nil
}

// usageLine renders a command as it is typed: positionals in catalog order,
// then flags.
func usageLine(cmd Command) string {
	var params struct {
		Required   []string                   `json:"required"`
		Properties map[string]json.RawMessage `json:"properties"`
	}
	_ = json.Unmarshal(cmd.Parameters, &params)
	required := map[string]bool{}
	for _, r := range params.Required {
		required[r] = true
	}
	positional := map[string]bool{}
	parts := []string{"dossier " + strings.ReplaceAll(cmd.ID, ".", " ")}
	for _, p := range cmd.Positional {
		positional[p] = true
		token := strings.ToUpper(p)
		var prop struct {
			Type string `json:"type"`
		}
		_ = json.Unmarshal(params.Properties[p], &prop)
		if prop.Type == "array" {
			token += "..."
		}
		if !required[p] {
			token = "[" + token + "]"
		}
		parts = append(parts, token)
	}
	var flags []string
	for name := range params.Properties {
		if !positional[name] {
			flags = append(flags, name)
		}
	}
	sort.Strings(flags)
	for _, name := range flags {
		var prop struct {
			Type string `json:"type"`
		}
		_ = json.Unmarshal(params.Properties[name], &prop)
		token := "--" + name
		if prop.Type != "boolean" {
			token += " " + strings.ToUpper(name)
		}
		if !required[name] {
			token = "[" + token + "]"
		}
		parts = append(parts, token)
	}
	return strings.Join(parts, " ")
}

// describeParameters lists a command's parameters with their descriptions.
func describeParameters(cmd Command) (string, error) {
	var params struct {
		Required   []string `json:"required"`
		Properties map[string]struct {
			Type        string `json:"type"`
			Description string `json:"description"`
		} `json:"properties"`
	}
	if err := json.Unmarshal(cmd.Parameters, &params); err != nil {
		return "", fmt.Errorf("%s: %w", cmd.ID, err)
	}
	if len(params.Properties) == 0 {
		return "none", nil
	}
	required := map[string]bool{}
	for _, r := range params.Required {
		required[r] = true
	}
	names := make([]string, 0, len(params.Properties))
	for name := range params.Properties {
		names = append(names, name)
	}
	sort.Strings(names)
	var out []string
	for _, name := range names {
		p := params.Properties[name]
		entry := "`" + name + "`"
		if required[name] {
			entry += " (required)"
		}
		if p.Description != "" {
			entry += ": " + strings.TrimSuffix(p.Description, ".")
		} else if p.Type == "array" {
			entry += ": one or more model files"
		}
		out = append(out, entry)
	}
	return strings.Join(out, "; "), nil
}

func mcpToolNames(catalog Catalog) string {
	var names []string
	for _, cmd := range catalog.Commands {
		if cmd.Surfaced("mcp") {
			names = append(names, "`"+ToolName(cmd.ID)+"`")
		}
	}
	sort.Strings(names)
	return strings.Join(names, ", ")
}
