package doors

import (
	"bytes"
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"

	"dossier/internal/kinds"
	"dossier/internal/model"
)

func init() { register("skill", skillDoor) }

// SkillResult is dossier.skill-result/v1.
type SkillResult struct {
	SchemaVersion string `json:"schema_version"`
	Markdown      string `json:"markdown,omitempty"`
	Written       string `json:"written,omitempty"`
}

func (r SkillResult) human(w io.Writer) {
	if r.Written != "" {
		say(w, "wrote %s\n", r.Written)
		return
	}
	say(w, "%s", r.Markdown)
}

func skillDoor(_ context.Context, args []string, _ io.Reader) Envelope {
	const id = "skill"
	fs := flag.NewFlagSet(id, flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	write := fs.String("write", "", "write SKILL.md here instead of printing it")
	positional, err := parseInterspersed(fs, args)
	if err != nil {
		return errorEnvelope(id, "usage", err)
	}
	if len(positional) != 0 {
		return errorEnvelope(id, "usage", fmt.Errorf("skill takes no positional arguments"))
	}
	md, err := Skill()
	if err != nil {
		return errorEnvelope(id, "render", err)
	}
	if *write != "" {
		if err := os.WriteFile(*write, md, 0o644); err != nil {
			return errorEnvelope(id, "write", err)
		}
		return Envelope{SchemaVersion: SchemaVersion, Command: id, Outcome: OutcomeOK, Result: SkillResult{SchemaVersion: "dossier.skill-result/v1", Written: *write}}
	}
	return Envelope{SchemaVersion: SchemaVersion, Command: id, Outcome: OutcomeOK, Result: SkillResult{SchemaVersion: "dossier.skill-result/v1", Markdown: string(md)}}
}

// Skill renders SKILL.md from the catalog and the kinds, so the skill can
// never describe a command or a facet that the binary does not have.
func Skill() ([]byte, error) {
	catalog, err := LoadCatalog()
	if err != nil {
		return nil, err
	}
	all, err := kinds.All()
	if err != nil {
		return nil, err
	}
	var b bytes.Buffer
	w := func(format string, args ...any) { say(&b, format, args...) }

	var kindIDs []string
	for _, k := range all {
		kindIDs = append(kindIDs, k.ID)
	}
	w("---\n")
	w("name: dossier\n")
	w("description: Turn one JSON model into one self-contained, agent-readable HTML dossier (%s) that a reader scans once, picks from by number, and hands back as decisions. Use when the user wants a doc, plan, brief, report, review packet, release or incident record, or any structured decision surface.\n", strings.Join(kindIDs, ", "))
	w("metadata:\n  short-description: Render JSON document models into self-contained HTML dossiers\n")
	w("---\n\n")
	w("# Dossier\n\n")
	w("Generated by `dossier skill` from the command catalog and the kind presets; do not edit by hand.\n\n")
	w("Dossier turns **one JSON model** into **one self-contained HTML file**: no server, no external requests, the model embedded as a JSON island so an agent reads one block instead of scraping. The reader gets a contents rail, collapsed items, a summary table, and a pick block that writes a reply line. You get the reply back as decisions.\n\n")

	w("## Five concepts\n\n")
	w("- **Kind** is a preset: the facets an item carries, the field vocabularies, the summary columns, and the pick text. Pick one from the table below.\n")
	w("- **Section** has a title and either content parts or a board. Part types: %s.\n", strings.Join(model.PartTypes, ", "))
	w("- **Item** is a numbered thing in a board: id, title, one-sentence summary, size, effort, impact, dependsOn, facets. A board with `\"layout\": \"rows\"` lists unnumbered entries.\n")
	w("- **Facet** is a labeled markdown body on an item, in the kind's fixed order.\n")
	w("- **Decision** is the only state: path, picked ids, notes by id.\n\n")

	w("## Kinds\n\n")
	w("| Kind | What it is | Facets, in order | Closers |\n| --- | --- | --- | --- |\n")
	for _, k := range all {
		facets := "any labels, until the vocabulary ships"
		if len(k.Items.Facets) > 0 {
			facets = strings.Join(k.Items.Facets, ", ")
		}
		closers := ""
		if len(k.Items.Closers) > 0 {
			closers = strings.Join(k.Items.Closers, ", ")
		}
		w("| `%s` | %s | %s | %s |\n", k.ID, k.Summary, facets, closers)
	}
	w("\nRisk and Note facets render in the risk color. Run `dossier describe --json` for the full presets.\n\n")

	w("## Content rules\n\n")
	w("- **Effort is agent time, never calendar time.** `S` is under an hour, `M` a few hours with review, `L` a day or more across sessions. Never write days-of-work or weeks-of-work.\n")
	w("- **Concise by default.** A summary is one sentence. A facet is two or three sentences. Kinds carry character limits; `validate` and `build` warn past them without blocking.\n")
	w("- **Detail sits behind a fold.** Items open collapsed, so the summary line must stand alone.\n")
	w("- **Ids** are lowercase letters, digits, and hyphens, unique across sections and items. `dependsOn` names item ids.\n")
	w("- **Markdown** in prose, facets, table cells, and spec text. Raw HTML is escaped. Fenced code is highlighted.\n")
	w("- **Figures** may use a path relative to the model file; `build` inlines it. Diagrams carry DOT or Mermaid source and render as source for now.\n\n")

	w("## Workflow\n\n")
	w("1. `dossier init KIND --title \"…\"` writes `<slug>.dossier.json` with the kind's facets in place.\n")
	w("2. Fill it in: one prose section that states the thesis, one board of items, each with a one-sentence summary and every facet.\n")
	w("3. `dossier validate <slug>.dossier.json`: findings block, warnings are advice.\n")
	w("4. `dossier build <slug>.dossier.json` writes `<slug>.html` beside it. Open it for the reader.\n")
	w("5. The reader replies with numbers, for example `1, 3, 4. Notes: 3: keep blue.` Apply it with `dossier decisions apply <slug>.dossier.json --reply \"…\"`, then rebuild.\n")
	w("6. `dossier decisions read <slug>.dossier.json` prints the decisions document for the next step.\n\n")
	w("Pass `--json` to any command for the `dossier.result/v1` envelope: `outcome` is `ok`, `findings`, or `error`; `findings` block, `warnings` do not. A 0.6 model file (`dossierVersion`, `blocks`) still builds, with one warning per aliased block; 0.8 removes the aliases.\n\n")

	w("## Commands\n\n")
	w("| Command | Does | Parameters |\n| --- | --- | --- |\n")
	for _, cmd := range catalog.Commands {
		if !cmd.Surfaced("skill") {
			continue
		}
		params, err := describeParameters(cmd)
		if err != nil {
			return nil, err
		}
		w("| `%s` | %s | %s |\n", usageLine(cmd), cmd.Summary, params)
	}
	w("\n`dossier mcp` serves the same commands as MCP tools over stdio, named %s, with the parameters above as their input schema and the same envelope as their answer.\n\n", mcpToolNames(catalog))

	w("## A starter model\n\n")
	brainstorm, err := kinds.Load("brainstorm")
	if err != nil {
		return nil, err
	}
	starter, err := model.Encode(Starter(brainstorm, "Twelve moves", "", ""))
	if err != nil {
		return nil, err
	}
	w("What `dossier init brainstorm --title \"Twelve moves\"` writes:\n\n```json\n%s```\n", starter)
	return b.Bytes(), nil
}

// usageLine renders a command as it is typed: positionals in catalog order,
// then flags.
func usageLine(cmd Command) string {
	var params struct {
		Required   []string                   `json:"required"`
		Properties map[string]json.RawMessage `json:"properties"`
	}
	_ = json.Unmarshal(cmd.Parameters, &params)
	required := map[string]bool{}
	for _, r := range params.Required {
		required[r] = true
	}
	positional := map[string]bool{}
	parts := []string{"dossier " + strings.ReplaceAll(cmd.ID, ".", " ")}
	for _, p := range cmd.Positional {
		positional[p] = true
		token := strings.ToUpper(p)
		var prop struct {
			Type string `json:"type"`
		}
		_ = json.Unmarshal(params.Properties[p], &prop)
		if prop.Type == "array" {
			token += "..."
		}
		if !required[p] {
			token = "[" + token + "]"
		}
		parts = append(parts, token)
	}
	var flags []string
	for name := range params.Properties {
		if !positional[name] {
			flags = append(flags, name)
		}
	}
	sort.Strings(flags)
	for _, name := range flags {
		var prop struct {
			Type string `json:"type"`
		}
		_ = json.Unmarshal(params.Properties[name], &prop)
		token := "--" + name
		if prop.Type != "boolean" {
			token += " " + strings.ToUpper(name)
		}
		if !required[name] {
			token = "[" + token + "]"
		}
		parts = append(parts, token)
	}
	return strings.Join(parts, " ")
}

// describeParameters lists a command's parameters with their descriptions.
func describeParameters(cmd Command) (string, error) {
	var params struct {
		Required   []string `json:"required"`
		Properties map[string]struct {
			Type        string `json:"type"`
			Description string `json:"description"`
		} `json:"properties"`
	}
	if err := json.Unmarshal(cmd.Parameters, &params); err != nil {
		return "", fmt.Errorf("%s: %w", cmd.ID, err)
	}
	if len(params.Properties) == 0 {
		return "none", nil
	}
	required := map[string]bool{}
	for _, r := range params.Required {
		required[r] = true
	}
	names := make([]string, 0, len(params.Properties))
	for name := range params.Properties {
		names = append(names, name)
	}
	sort.Strings(names)
	var out []string
	for _, name := range names {
		p := params.Properties[name]
		entry := "`" + name + "`"
		if required[name] {
			entry += " (required)"
		}
		if p.Description != "" {
			entry += ": " + strings.TrimSuffix(p.Description, ".")
		} else if p.Type == "array" {
			entry += ": one or more model files"
		}
		out = append(out, entry)
	}
	return strings.Join(out, "; "), nil
}

func mcpToolNames(catalog Catalog) string {
	var names []string
	for _, cmd := range catalog.Commands {
		if cmd.Surfaced("mcp") {
			names = append(names, "`"+ToolName(cmd.ID)+"`")
		}
	}
	sort.Strings(names)
	return strings.Join(names, ", ")
}
