package doors

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"strings"

	"dossier/internal/schema"
)

func init() { register("types", typesDoor) }

// TypesResult is dossier.types-result/v1.
type TypesResult struct {
	SchemaVersion string `json:"schema_version"`
	TypeScript    string `json:"typescript,omitempty"`
	Written       string `json:"written,omitempty"`
}

func (r TypesResult) human(w io.Writer) {
	if r.Written != "" {
		say(w, "wrote %s\n", r.Written)
		return
	}
	say(w, "%s", r.TypeScript)
}

func typesDoor(_ context.Context, in Input) Envelope {
	const id = "types"
	fs := flag.NewFlagSet(id, flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	write := fs.String("write", "", "write the declarations here instead of printing them")
	positional, err := parseInterspersed(fs, in.Args)
	if err != nil {
		return errorEnvelope(id, "usage", err)
	}
	if len(positional) != 0 {
		return errorEnvelope(id, "usage", fmt.Errorf("types takes no positional arguments"))
	}
	ts, err := TypeScript()
	if err != nil {
		return errorEnvelope(id, "render", err)
	}
	result := TypesResult{SchemaVersion: "dossier.types-result/v1"}
	if *write == "" {
		result.TypeScript = string(ts)
	} else {
		if err := os.WriteFile(*write, ts, 0o644); err != nil {
			return errorEnvelope(id, "write", err)
		}
		result.Written = *write
	}
	return Envelope{SchemaVersion: SchemaVersion, Command: id, Outcome: OutcomeOK, Result: result}
}

// TypeScript renders declarations for dossier.model/v1 and dossier.result/v1
// from the embedded JSON Schemas, keeping their property order and
// descriptions, so typed consumers can never drift from the validator.
func TypeScript() ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Generated by `dossier types` from the dossier.model/v1 and dossier.result/v1\n// JSON Schemas. Do not edit; run make generate in core/.\n")
	for _, s := range []struct {
		raw    []byte
		root   string
		inline map[string]string
	}{
		{schema.ModelSchemaJSON(), "DossierModel", map[string]string{"meta": "Meta"}},
		{schema.ResultSchemaJSON(), "DossierResult", map[string]string{"result": "ResultBody", "error": "ResultError"}},
	} {
		root, err := parseOrdered(s.raw)
		if err != nil {
			return nil, err
		}
		g := &tsGen{out: &b, inline: s.inline}
		g.named(s.root, root)
		if defs := root.get("$defs"); defs != nil {
			for _, kv := range defs.fields {
				g.named(pascal(kv.key), kv.value)
			}
		}
	}
	return b.Bytes(), nil
}

// node is a JSON value that remembers object key order.
type node struct {
	fields []field
	items  []*node
	scalar any
	kind   byte // o object, a array, s scalar
}

type field struct {
	key   string
	value *node
}

func (n *node) get(key string) *node {
	if n == nil {
		return nil
	}
	for _, f := range n.fields {
		if f.key == key {
			return f.value
		}
	}
	return nil
}

func (n *node) str(key string) string {
	if v := n.get(key); v != nil {
		if s, ok := v.scalar.(string); ok {
			return s
		}
	}
	return ""
}

func parseOrdered(data []byte) (*node, error) {
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.UseNumber()
	return parseNode(dec)
}

func parseNode(dec *json.Decoder) (*node, error) {
	tok, err := dec.Token()
	if err != nil {
		return nil, err
	}
	switch t := tok.(type) {
	case json.Delim:
		switch t {
		case '{':
			n := &node{kind: 'o'}
			for dec.More() {
				keyTok, err := dec.Token()
				if err != nil {
					return nil, err
				}
				key, ok := keyTok.(string)
				if !ok {
					return nil, errors.New("schema object key is not a string")
				}
				v, err := parseNode(dec)
				if err != nil {
					return nil, err
				}
				n.fields = append(n.fields, field{key, v})
			}
			_, err := dec.Token()
			return n, err
		case '[':
			n := &node{kind: 'a'}
			for dec.More() {
				v, err := parseNode(dec)
				if err != nil {
					return nil, err
				}
				n.items = append(n.items, v)
			}
			_, err := dec.Token()
			return n, err
		}
		return nil, fmt.Errorf("unexpected delimiter %v", t)
	default:
		return &node{kind: 's', scalar: t}, nil
	}
}

type tsGen struct {
	out    *bytes.Buffer
	inline map[string]string
	queued []queuedType
}

type queuedType struct {
	name string
	n    *node
}

// named writes an exported interface for an object schema, or a type alias
// for anything else, then any inline object types it named.
func (g *tsGen) named(name string, n *node) {
	g.out.WriteString("\n")
	g.doc(n, "")
	if n.str("type") == "object" && n.get("properties") != nil {
		g.out.WriteString("export interface " + name + " {\n")
		g.properties(n, "  ", true)
		if open(n) {
			g.out.WriteString("  [key: string]: unknown;\n")
		}
		g.out.WriteString("}\n")
	} else {
		g.out.WriteString("export type " + name + " = " + g.expr(n, "") + ";\n")
	}
	for len(g.queued) > 0 {
		q := g.queued[0]
		g.queued = g.queued[1:]
		g.named(q.name, q.n)
	}
}

func (g *tsGen) properties(n *node, indent string, top bool) {
	required := map[string]bool{}
	if req := n.get("required"); req != nil {
		for _, r := range req.items {
			if s, ok := r.scalar.(string); ok {
				required[s] = true
			}
		}
	}
	for _, p := range n.get("properties").fields {
		g.doc(p.value, indent)
		opt := "?"
		if required[p.key] {
			opt = ""
		}
		var typ string
		if name, ok := g.inline[p.key]; ok && top && p.value.str("type") == "object" {
			g.queued = append(g.queued, queuedType{name, p.value})
			typ = name
		} else {
			typ = g.expr(p.value, indent)
		}
		g.out.WriteString(indent + tsKey(p.key) + opt + ": " + typ + ";\n")
	}
}

// expr renders a schema as a TypeScript type expression.
func (g *tsGen) expr(n *node, indent string) string {
	if ref := n.str("$ref"); ref != "" {
		return pascal(ref[strings.LastIndex(ref, "/")+1:])
	}
	if c := n.get("const"); c != nil {
		return literal(c)
	}
	if e := n.get("enum"); e != nil {
		parts := make([]string, len(e.items))
		for i, v := range e.items {
			parts[i] = literal(v)
		}
		return strings.Join(parts, " | ")
	}
	switch n.str("type") {
	case "string":
		return "string"
	case "number", "integer":
		return "number"
	case "boolean":
		return "boolean"
	case "array":
		if items := n.get("items"); items != nil {
			inner := g.expr(items, indent)
			if strings.ContainsAny(inner, " {") {
				return "Array<" + inner + ">"
			}
			return inner + "[]"
		}
		return "unknown[]"
	case "object":
		if n.get("properties") != nil {
			var b bytes.Buffer
			sub := &tsGen{out: &b, inline: nil}
			sub.properties(n, indent+"  ", false)
			rest := ""
			if open(n) {
				rest = indent + "  [key: string]: unknown;\n"
			}
			return "{\n" + b.String() + rest + indent + "}"
		}
		if ap := n.get("additionalProperties"); ap != nil && ap.kind == 'o' {
			return "Record<string, " + g.expr(ap, indent) + ">"
		}
		return "Record<string, unknown>"
	}
	return "unknown"
}

func (g *tsGen) doc(n *node, indent string) {
	if d := n.str("description"); d != "" {
		g.out.WriteString(indent + "/** " + strings.ReplaceAll(d, "*/", "* /") + " */\n")
	}
}

// open reports whether an object schema allows properties it does not list.
func open(n *node) bool {
	ap := n.get("additionalProperties")
	return ap == nil || (ap.kind == 's' && ap.scalar == true)
}

func literal(n *node) string {
	b, err := json.Marshal(n.scalar)
	if err != nil {
		return "unknown"
	}
	return string(b)
}

func tsKey(k string) string {
	for i, c := range k {
		if !(c == '_' || c == '$' || (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (i > 0 && c >= '0' && c <= '9')) {
			return fmt.Sprintf("%q", k)
		}
	}
	return k
}

func pascal(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool { return r == '-' || r == '_' || r == '.' })
	for i, p := range parts {
		if p != "" {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}
