// Generated by `dossier types` from the dossier.model/v1 and dossier.result/v1
// JSON Schemas. Do not edit; run make generate in core/.

/** One Dossier document: a kind, metadata, ordered sections with content parts or a board of items, and the reader's decisions. */
export interface DossierModel {
  dossier: "1.0";
  kind: string;
  meta: Meta;
  sections: Section[];
  decisions?: Decisions;
}

export interface Meta {
  title: string;
  slug: string;
  kicker?: string;
  /** One word of the title set in the italic serif accent. */
  emphasis?: string;
  lede?: string;
  updated?: string;
  status?: string;
  /** Opt in to web fonts. Omitted means the system stack and zero external requests. */
  fonts?: "google";
  /** Document-level figures shown first in the masthead strip, such as severity or version. */
  facts?: Array<{
    label: string;
    value: string;
    tone?: "teal" | "violet" | "risk" | "neutral";
  }>;
}

export type Id = string;

export interface Section {
  id: Id;
  title: string;
  parts?: Part[];
  board?: Board;
}

export interface Part {
  type: "prose" | "spec" | "table" | "callout" | "code" | "figure" | "diagram" | "chart";
  title?: string;
  tone?: "note" | "risk";
  markdown?: string;
  columns?: string[];
  rows?: string[][];
  spec?: Array<{
    label: string;
    text: string;
  }>;
  note?: string;
  lang?: string;
  code?: string;
  /** Figure image: a path relative to the model file, a data:image URI, or an http(s) URL. Relative paths are inlined at build time. */
  src?: string;
  alt?: string;
  caption?: string;
  /** Diagram source in the given format. */
  source?: string;
  format?: "dot" | "mermaid";
  variant?: "bar" | "line" | "area";
  data?: Array<{
    label: string;
    value: number;
  }>;
}

export interface Board {
  /** Render a summary table before the items. */
  summary?: boolean;
  layout?: "articles" | "rows";
  items: Item[];
}

export interface Item {
  id: Id;
  title: string;
  summary?: string;
  size?: string;
  category?: string;
  severity?: string;
  status?: string;
  effort?: string;
  impact?: number;
  owner?: string;
  required?: boolean;
  dependsOn?: Id[];
  facets?: Array<{
    label: string;
    markdown: string;
  }>;
}

export interface Decisions {
  path?: string;
  picked?: Id[];
  notes?: Record<string, string>;
}

/** The one envelope every door returns on every surface: an outcome, a result, findings that block, warnings that do not, and an error body. */
export interface DossierResult {
  schema_version: "dossier.result/v1";
  command: string;
  outcome: "ok" | "findings" | "error";
  result?: ResultBody;
  findings?: Problem[];
  warnings?: Problem[];
  error?: ResultError;
}

export interface ResultBody {
  schema_version: string;
  [key: string]: unknown;
}

export interface ResultError {
  code: string;
  message: string;
}

export interface Problem {
  path: string;
  message: string;
}
