package diagram

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"dossier/internal/model"
)

func TestMermaidTranslationGoldens(t *testing.T) {
	inputs, err := filepath.Glob(filepath.Join("..", "..", "testdata", "diagrams", "*.mmd"))
	if err != nil || len(inputs) < 3 {
		t.Fatalf("inputs: %v %v", inputs, err)
	}
	for _, in := range inputs {
		src, err := os.ReadFile(in)
		if err != nil {
			t.Fatal(err)
		}
		dot, notes, err := MermaidToDOT(string(src))
		got := dot
		if err != nil {
			got = "error: " + err.Error() + "\n"
		}
		for _, n := range notes {
			got += "// note: " + n + "\n"
		}
		golden := strings.TrimSuffix(in, ".mmd") + ".dot"
		if os.Getenv("UPDATE_GOLDEN") != "" {
			if err := os.WriteFile(golden, []byte(got), 0o644); err != nil {
				t.Fatal(err)
			}
		}
		want, err := os.ReadFile(golden)
		if err != nil {
			t.Fatalf("%s: no golden (run with UPDATE_GOLDEN=1): %v", in, err)
		}
		if got != string(want) {
			t.Errorf("%s differs from its golden; review, then run with UPDATE_GOLDEN=1\n%s", filepath.Base(in), got)
		}
	}
}

func TestMermaidErrorsSayWhatToFix(t *testing.T) {
	for src, want := range map[string]string{
		"":                                 "the Mermaid source is empty",
		"pie\n  \"a\": 1":                  "only Mermaid flowcharts render, and this is a pie",
		"flowchart sideways\n a --> b":     `flowchart direction "sideways" is not TB, TD, BT, LR, or RL`,
		"flowchart\n subgraph s\n a --> b": `subgraph "s" has no end`,
		"flowchart\n end":                  "line 2 of the Mermaid source: end without a subgraph",
		"flowchart\n a ~~> b":              `expected a link such as --> at "~~> b"`,
		"flowchart\n a -- label b":         `the link label after "--" needs a closing link`,
		"flowchart\n a -->|open b":         "a link label opened with | needs a closing |",
		"flowchart\n --> b":                `expected a node id at "--> b"`,
	} {
		_, _, err := MermaidToDOT(src)
		if err == nil || !strings.Contains(err.Error(), want) {
			t.Errorf("%q: got %v, want %q", src, err, want)
		}
	}
}

func TestDefaultsGoFirstInTheGraphBody(t *testing.T) {
	for src, prefix := range map[string]string{
		"digraph { a -> b }":                       "digraph {\n" + defaults,
		"strict digraph \"x { y\" { a }":           "strict digraph \"x { y\" {\n" + defaults,
		"/* { */ graph g { a -- b }":               "/* { */ graph g {\n" + defaults,
		"// comment {\ndigraph { a }":              "// comment {\ndigraph {\n" + defaults,
		"#line 1 {\ndigraph { a [color=\"#f{\"] }": "#line 1 {\ndigraph {\n" + defaults,
	} {
		got, err := withDefaults(src)
		if err != nil || !strings.HasPrefix(got, prefix) {
			t.Errorf("%q:\n%s", src, got)
		}
	}
	if _, err := withDefaults("digraph"); err == nil {
		t.Error("a graph without a body is an error")
	}
}

func TestRestyleKeepsGeometryAndDropsEverythingElse(t *testing.T) {
	raw := `<?xml version="1.0"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz -->
<svg width="62pt" height="116pt" viewBox="0.00 0.00 62.00 116.00" onload="alert(1)" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<script>alert(1)</script>
<style>svg { display: none }</style>
<defs><linearGradient id="l_1"><stop offset="0" stop-color="red"/></linearGradient></defs>
<g id="graph0" class="graph mine" transform="scale(1 1) rotate(0) translate(4 112)">
<title>G</title>
<polygon fill="white" stroke="none" points="-4,4 -4,-112 58,-112 58,4 -4,4"/>
<g id="node1" class="node teal extra">
<title>x</title>
<a xlink:href="https://example.com" xlink:title="x" target="_blank">
<ellipse fill="url(#l_1)" stroke="black" cx="27" cy="-90" rx="27" ry="18"/>
<text text-anchor="middle" x="27" y="-85.8" font-family="Times,serif" font-size="14.00" font-weight="bold">x &amp; &lt;y&gt;</text>
</a>
</g>
<g id="edge1" class="edge">
<path fill="none" stroke="black" stroke-dasharray="5,2" d="M27,-71.7C27,-64.41 27,-55.73 27,-47.54"/>
<polygon fill="none" stroke="black" points="30.5,-47.62 27,-37.62 23.5,-47.62"/>
<foreignObject><div>html</div></foreignObject>
<image href="https://example.com/x.png" width="1" height="1"/>
</g>
</g>
</svg>`
	svg, err := Restyle([]byte(raw), `Flow "one"`, "dabc")
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		`<svg class="dg" role="img" aria-label="Flow &#34;one&#34;" width="62pt" height="116pt" viewBox="0.00 0.00 62.00 116.00">`,
		`<g id="dabc-graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 112)">`,
		`<g id="dabc-node1" class="node teal"><ellipse cx="27" cy="-90" rx="27" ry="18"></ellipse><text text-anchor="middle" x="27" y="-85.8" font-weight="bold">x &amp; &lt;y&gt;</text></g>`,
		`<path stroke-dasharray="5,2" d="M27,-71.7C27,-64.41 27,-55.73 27,-47.54"></path>`,
		`<polygon class="hollow" points="30.5,-47.62 27,-37.62 23.5,-47.62"></polygon>`,
	} {
		if !strings.Contains(svg, want) {
			t.Errorf("restyled svg lacks %s\n%s", want, svg)
		}
	}
	for _, gone := range []string{"script", "alert", "style", "defs", "Gradient", "title", "href", "example.com", "foreignObject", "html", "image", "fill=", "stroke=", "font-family", "font-size", "onload", "mine", "extra", "<a", "-4,4 -4,-112"} {
		if strings.Contains(svg, gone) {
			t.Errorf("restyled svg still has %q", gone)
		}
	}
}

func TestRenderLaysOutDOTAndMermaid(t *testing.T) {
	r := &Renderer{}
	ctx := context.Background()
	dot := `digraph { rankdir=LR; app [label="Rider app"]; api [class="accent"]; app -> api [label="book"] }`
	svg, notes := r.Render(ctx, "dot", dot, "Booking", model.DiagramKey("dot", dot))
	if len(notes) > 0 || !strings.HasPrefix(svg, `<svg class="dg" role="img" aria-label="Booking"`) || !strings.Contains(svg, `>Rider app</text>`) || !strings.Contains(svg, `class="node accent"`) {
		t.Fatalf("dot render: %v\n%s", notes, svg)
	}
	again, _ := r.Render(ctx, "dot", dot, "Booking", model.DiagramKey("dot", dot))
	if again != svg {
		t.Error("a cached diagram renders the same")
	}
	mermaid := "flowchart TD\n  a[Payment times out] --> b{Hold exists?}\n  b -- yes --> c([Reuse the hold]):::teal"
	svg, notes = r.Render(ctx, "mermaid", mermaid, "", model.DiagramKey("mermaid", mermaid))
	if len(notes) > 0 || !strings.Contains(svg, ">Hold exists?</text>") || !strings.Contains(svg, `class="node teal"`) {
		t.Errorf("mermaid render: %v\n%s", notes, svg)
	}
	for format, source := range map[string]string{"dot": "digraph { a -> }", "mermaid": "sequenceDiagram\n a->>b: hi", "plantuml": "@startuml"} {
		svg, notes := r.Render(ctx, format, source, "", model.DiagramKey(format, source))
		if svg != "" || len(notes) != 1 || !strings.HasSuffix(notes[0], "shows as source") {
			t.Errorf("%s %q: %q %v", format, source, svg, notes)
		}
	}
	doc := &model.Document{Sections: []model.Section{{ID: "s", Parts: []model.Part{
		{Type: "prose", Markdown: "x"},
		{Type: "diagram", Source: dot},
		{Type: "diagram", Format: "mermaid", Source: "pie\n \"a\": 1"},
	}}}}
	diagrams, warnings := r.Document(ctx, doc)
	if len(diagrams) != 1 || diagrams[model.DiagramKey("dot", dot)] == "" || len(warnings) != 1 || warnings[0].Path != "/sections/0/parts/2/source" {
		t.Errorf("document: %d diagrams, warnings %v", len(diagrams), warnings)
	}
}
